" Custom Vim configuration

set number
set shiftwidth=4  " 1 tab === 4 spaces
set tabstop=2     " tab spacing
set ai            " Auto indent
set encoding=UTF-8
map <C-b> :NERDTreeToggle<CR>

call plug#begin('~/.vim/Plug')

" Themes
Plug 'arcticicestudio/nord-vim'
Plug 'ryanoasis/vim-devicons' "Icons for filetypes
Plug 'vim-airline/vim-airline' "Status bar
Plug 'vim-airline/vim-airline-themes' "Applicable themes

" Language Syntax Support
Plug 'pangloss/vim-javascript' "JS highlighting
Plug 'mxw/vim-jsx' "JSX syntax highlighting
Plug 'jparise/vim-graphql' "graphql syntax highlighting
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }

" Tools
Plug 'mitermayer/vim-prettier'
Plug 'jiangmiao/auto-pairs' "Autocomplete brackets. 
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive' "Git tools

Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'} "Nerdtree
Plug 'neoclide/coc.nvim', {'branch': 'release'} "autocompletion
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-rmarkdown'


" All of your Plugins must be added before the following line
call plug#end()            " required

" Render rmarkdown by pressing F5
autocmd Filetype rmd map <F5> :!R -e "rmarkdown::render('<c-r>%')"<enter>

colorscheme nord

let g:airline_powerline_fonts = 1 "for vim-airline symbols
let g:tex_conceal = "admg"
